[tool.poetry]
name = "promptgen"
version = "1.0.0"
description = ""
authors = ["zawakin <zawawahoge@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "promptgen" }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^1.10.7"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pytest-watch = "^4.2.0"
pytest-mock = "^3.10.0"
pytest-cov = "^4.0.0"
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"
pytest = "^7.3.1"
ipykernel = "^6.23.1"
pyproject-flake8 = "^6.0.0.post1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
openai = "^0.27.7"
jupyter = "^1.0.0"
python-dotenv = "^1.0.0"
colorama = "^0.4.6"
mkdocs = "^1.4.3"
pygments = "^2.15.1"
pymdown-extensions = "^10.0.1"
mkdocs-material = "^9.1.15"
typer = "^0.9.0"
pyyaml = "^6.0"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
