[tool.poetry]
name = "promptgen"
version = "0.1.0"
description = ""
authors = ["zawakin <zawawahoge@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "promptgen" }]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = ">=1.6.2,!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.1.3,<8.0.0"
mypy = "==0.982"
black = "^23.3.0"
isort = ">=5.0.6,<6.0.0"
flake8 = ">=3.8.4,<4.0.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = ">=1.1.2,<2.0.0"
pygments = "^2.15.1"
pymdown-extensions = "^10.0.1"
mkdocs-material = ">=8.1.4,<9.0.0"
typer = "^0.9.0"
pyyaml = "^6.0"
openai = "^0.27.7"
python-dotenv = "0.21.1"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
