# based on https://github.com/langchain-ai/langchain/blob/129d056085c44e9f4477feddcc6deffe2502d5c5/.github/ISSUE_TEMPLATE/bug-report.yml

name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve PromptoGen
labels: ["Bug Report"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few moments to check the issue tracker
        for existing issues about the bug.

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system info with us.
      placeholder: PromptoGen version, platform, python version, ...
    validations:
      required: true

  - type: checkboxes
    id: information-scripts-examples
    attributes:
      label: Information
      description: "The problem arises when using:"
      options:
        - label: "The official example scripts"
        - label: "My own modified scripts"

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a [code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        If you have code snippets, error messages, stack traces please provide them here as well.
        Important! Use code tags to correctly format your code. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting
        Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.

      placeholder: |
        Steps to reproduce the behavior:

          1.
          2.
          3.

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."
