# based on https://github.com/langchain-ai/langchain/blob/129d056085c44e9f4477feddcc6deffe2502d5c5/.github/ISSUE_TEMPLATE/feature-request.yml

name: "\U0001F680 Feature request"
description: Submit a proposal/request for a new PromptoGen feature
labels: ["02 Feature Request"]
body:
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Feature request
      description: |
        A clear and concise description of the feature proposal. Please provide links to any relevant GitHub repos, papers, or other resources if relevant.

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.

  - type: textarea
    id: contribution
    validations:
      required: true
    attributes:
      label: Your contribution
      description: |
        Is there any way that you could help, e.g. by submitting a PR? Make sure to read the CONTRIBUTING.MD [readme](https://github.com/zawakin/promptogen/blob/main/.github/CONTRIBUTING.md)
