site_name: PromptoGen
site_url: https://promptogen.zawakin.dev/ja/en/
repo_url: https://github.com/zawakin/promptogen
nav:
- PromptoGen: index.md
- Languages:
  - ja: /
  - en: /en/
- Tutorial:
  - tutorial.md
- Introduction:
  - introduction/hello.md
theme:
  name: material
  font:
    text: Roboto
  logo: https://promptogen.zawakin.dev/https://promptogen.zawakin.dev/https://localhost.svg
  favicon: https://promptogen.zawakin.dev/https://promptogen.zawakin.dev/https://localhost/favicon.png
  language: en
markdown_extensions:
- admonition: null
- codehilite: null
- pymdownx.keys: null
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite: null
- pymdownx.snippets: null
- pymdownx.superfences: null
extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/fastapi
  alternate:
  - link: /
    name: en - English
  - link: /en/
    name: en
