site_name: PromptoGen
site_url: https://promptogen.zawakin.dev/
repo_url: https://github.com/zawakin/promptogen
edit_uri: edit/main/docs/en/docs/
nav:
- PromptoGen: index.md
- Getting Started:
  - Installation: getting-started/installation.md
  - Quick Start: getting-started/quickstart.md
  - What is PromptoGen?: getting-started/overview.md
  - Understanding the Basic Model:
    - Value Class: getting-started/value.md
    - Prompt Class: getting-started/prompt.md
  - How to Use:
    - Format Value: getting-started/format-value.md
    - Parse Value: getting-started/parse-value.md
    - Format Prompt: getting-started/format-prompt.md
    - Parse LLM Output: getting-started/parse-prompt-output.md
  - Useful Features:
    - TextLLM Interface: getting-started/text-llm.md
    - Use PromptRunner: getting-started/prompt-runner.md
  - Concepts:
    - Concepts: concepts/concept.md
- Application Examples:
  - Examples: examples/index.md
  - Collaboration with LLM:
    - OpenAITextLLM: examples/openai-text-llm.md
  - Auto-prompt Generation:
    - Context QA: examples/context-qa.md
    - Task Splitting: examples/task-splitter.md
  - LLM Inference Process Output:
    - Reasoning for Input/Output (Context QA): examples/context-qa-reasoning.md
    - Adding Reasoning Process to Prompt: examples/prompt-reasoning.md
- Contribution Guide: contributing.md
- Language: language.md
theme:
  name: material
  theme: null
  palette:
  - scheme: default
    primary: black
    accent: black
  - scheme: slate
    primary: indigo
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - header.autohide
  - content.tooltips
  - navigation.expand
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  logo: /img/icon-white.svg
  favicon: /img/favicon.png
  icon:
    logo: logo
  language: en
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.snippets:
    base_path: ../../docs_src
    dedent_subsections: True
- pymdownx.superfences: null
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg
    emoji_index: !!python/name:materialx.emoji.twemoji
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo_url_shorthand: true
    user: squidfunk
    repo: mkdocs-material
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/zawawahoge
  alternate:
  - link: /
    name: en - English
  - link: /ja/
    name: ja - 日本語
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
extra_css:
  - "stylesheets/extra.css"
