name: release

on:
  push:
    tags:
      - "v*"

env:
  POETRY_VERSION: "1.5.1"
  PYTHON_VERSION: "3.11"
  WORKING_DIRECTORY: "promptogen"
  RELEASE_BRANCH: "main"

jobs:
  release:
    if: github.repository == 'zawakin/promptogen'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: "release-v2"
          install-command: |
              echo "Running core tests, installing dependencies with poetry..."
              poetry install

              echo "Install poetry-dynamic-versioning"
              poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Build project for distribution
        run: poetry build
      - name: Check Version
        id: check-version
        run: |
          # check tag and version
          echo $GITHUB_REF_NAME
          echo $(poetry version --short)
          if [ "$(echo $GITHUB_REF_NAME | cut -d'/' -f3)" != "v$(poetry version --short)" ]; then
            echo "Tag and version are not matched."
            exit 1
          fi
          echo version=$(poetry version --short) >> $GITHUB_OUTPUT
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generateReleaseNotes: true
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --dry-run
