name: Python CI

# ref. https://github.com/tiangolo/fastapi/blob/46726aa1c418ba2838187678d08860950fc0c3c3/.github/workflows/test.yml

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  POETRY_VERSION: "1.5.1"
  POETRY_URL: https://install.python-poetry.org

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: "test-v1"
          install-command: |
              echo "Running core tests, installing dependencies with poetry..."
              poetry install
      - name: Run tests with pytest
        run: |
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=promptogen tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Lint with flake8
        run: |
          poetry run flake8 promptogen

      - name: Test with mypy
        run: |
          poetry run mypy promptogen

      - name: Check code formatting with Black
        run: |
          poetry run black --check promptogen

      - name: Check import formatting with isort
        run: |
          poetry run isort --check-only promptogen
