from typing import Callable, List, Tuple

import promptogen as pg
from examples.llm.openai_util import OpenAITextLLM
from promptogen.model.prompt_interceptor import PromptInterceptor
from promptogen.prompt_collection.prompts.text_summarizer import TextSummarizerPrompt
from promptogen.prompt_interceptor.translation_interceptor import ValueTranslationInterceptor

formatter = pg.KeyValuePromptFormatter()
llm = OpenAITextLLM(model="gpt-3.5-turbo")

interceptors: List[PromptInterceptor] = [
    ValueTranslationInterceptor(llm=llm, from_lang="Japanese", to_lang="English"),
]

prompt_runner = pg.TextLLMPromptRunner(llm=llm, formatter=formatter, interceptors=interceptors)

text_summarizer = TextSummarizerPrompt()

# This heart-warming text is generated by ChatGPT:
# A large tree stands in the center of the park.
# For many decades, no, for hundreds of years, this old tree has marked the passage of time and welcomed numerous visitors during the changing seasons.
# Children climb its big branches during summer vacation, gather fallen leaves beneath it in autumn, quietly pass the time under its snowy embrace in winter, and once again come to life adorned with fresh greenery in spring.\nOne day, a little boy and his friends began a treasure hunt under this tree. After digging for a while, they found a small time capsule. Inside were letters and photographs left behind by children from several decades ago. The photographs depicted scenes from the park in the past, and the smiling faces of children posing with the majestic tree.
# The boys were both surprised and filled with understanding that many memories rested beneath the shade of this tree. Regardless of the era, the children who played under this tree laughed and enjoyed adventures under the same sky.\nThrough the passage of time, this grand tree quietly watches over its place in history. The past, the present, and the future.
text = """公園の中心に立つ大きな樹。何十年、いや何百年と時を刻んできた老木は、季節の変わり目に数多の訪問者を迎えてきた。子供たちが夏休みにはその大きな枝に登り、秋にはその下で落ち葉を集め、冬には雪を被って静かに時を過ごし、春には新緑を纏い再び命を宿す。
ある日、小さな男の子が、友達と共に木の下で宝探しを始めた。掘り始めてしばらくすると、小さなタイムカプセルを見つけた。中には、数十年前の子供たちが残した手紙と写真が入っていた。写真には昔の公園の風景と、その大木とともに笑顔で写る子供たちの姿。
男の子たちは驚きと共に、この大木の下には多くの思い出が埋もれていることを理解した。それぞれの時代で、この木の下で遊んだ子供たちは、同じ空の下で笑い、冒険を楽しんでいたのだ。
時代は移り変わっても、この大木は静かにその場所で歴史を見守り続けている。過去も現在も、そして未来も。"""

resp = prompt_runner.run_prompt(
    text_summarizer,
    input_value={
        "text": text,
    },
)
print(resp["summary"])
